# Generated by Django 4.1.1 on 2022-11-02 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("back-end", "back-end"),
                            ("front-end", "front-end"),
                            ("iOS", "iOS"),
                            ("Android", "android"),
                        ],
                        default="back-end",
                        max_length=10,
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=255)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "BUG"),
                            ("AMELIORATION", "AMELIORATION"),
                            ("TACHE", "TACHE"),
                        ],
                        default="BUG",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "FAIBLE"),
                            ("MOYENNE", "MOYENNE"),
                            ("ELEVEE", "ELEVEE"),
                        ],
                        default="MOYENNE",
                        max_length=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A faire", "A faire"),
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                        ],
                        default="A faire",
                        max_length=8,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee_user",
                    models.ForeignKey(
                        default=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="author_issues",
                            to=settings.AUTH_USER_MODEL,
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="tracking.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("auteur", "auteur"),
                            ("collaborateur", "collaborateur"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("auteur", "auteur"),
                            ("collaborateur", "collaborateur"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_contributor",
                        to="tracking.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tracking.issue",
                    ),
                ),
            ],
        ),
    ]
