# Generated by Django 4.1.1 on 2022-11-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contributor", name="permission",),
    ]
